# Generated by Django 5.1.2 on 2024-10-28 23:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_creada', models.DateTimeField(auto_now_add=True)),
                ('categoria_actualizada', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_creado', models.DateTimeField(auto_now_add=True)),
                ('historial_actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('preparación', 'Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='preparación', max_length=20)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MesasEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mesa_creado', models.DateTimeField(auto_now_add=True)),
                ('estado_mesa_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago_creado', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago_actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_compra', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_creado', models.DateTimeField(auto_now_add=True)),
                ('rol_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_creado', models.DateTimeField(auto_now_add=True)),
                ('menu_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriamenu')),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_creada', models.DateTimeField(auto_now_add=True)),
                ('mesa_actualizada', models.DateTimeField(auto_now=True)),
                ('numero_mesa', models.IntegerField()),
                ('capacidad_mesa', models.IntegerField()),
                ('disponiblilidad_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesasestado')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('factura_actualizada', models.DateTimeField(auto_now=True)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesas')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_creado', models.DateTimeField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.historialestados')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_pedido_creado', models.DateTimeField(auto_now_add=True)),
                ('detalle_pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion_creado', models.DateTimeField(auto_now_add=True)),
                ('promocion_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('descuento', models.IntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_creada', models.DateTimeField(auto_now_add=True)),
                ('reserva_actualizada', models.DateTimeField(auto_now=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesas')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_creada', models.DateTimeField(auto_now_add=True)),
                ('notificacion_actualizada', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField()),
                ('id_usuario_notificaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_creado', models.DateTimeField(auto_now_add=True)),
                ('comentario_actualizado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('id_menu_comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('id_usuario_comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
